### ISSUE TITLE
Make smooth transition examples

### ISSUE THREAD

**Issue by qwiglydee** [qwiglydee/otree-front-ext#6]
Use cases:
- transition of trials
- transition of stages 

```css
.fade-out {
  opacity: 0;
  transition: opacity 100ms easy-out;
}

fade-in {
  opacity: 1;
  transition: opacity 50ms easy-in;
}
```

```javascript
function transitDisplays(switching_params) {
  // put fade-out class to off-elems
  // delay switchDisplay by fadeout time, with the same params
  // schedule putting fade-in class to on-elems
})
```
